In [4]:
import torch


### **張量（Tensor）**
是數學和計算科學中的一個基本概念，用於表示**多維數據結構**。在機器學習和深度學習中，張量是數據的基本表示形式，類似於標量、向量和矩陣，但可以擁有更多的維度。

#### 1. **處理更高維度的數據**
**圖像數據：** 圖像數據通常是三維（高度、寬度、通道），如果再考慮批量處理（batch processing），就需要四維張量。
例如，一批 32 個彩色圖像，每個圖像大小為 64x64 像素，這可以表示為形狀為 (32,64,64,3) 的四維張量。

**視頻數據：** 視頻數據通常是四維（幀數、高度、寬度、通道），再加上批次維度就是五維張量。

**自然語言處理：** 文本數據在表示為嵌入（embedding）時，通常需要三維張量（批量大小、序列長度、嵌入維度）。


#### **2. 更靈活的數據操作**
**廣播機制：** 張量操作支持廣播機制，使得不同形狀的張量之間可以進行運算，而不需要明確地對齊它們的形狀。

**高效計算：** 深度學習框架（如 TensorFlow 和 PyTorch）對張量操作進行了高度優化，利用 GPU 加速，提供了高效的數值計算。

In [8]:
x = torch.tensor(87)
y = torch.tensor([[1, 2], [3, 4]])
z = torch.tensor([[[1,2,3],[1,2,3]]])
y.ndim
z.shape#第一個[]中有一個值 第二個[]有兩個值 第三個[]有三個值

torch.Size([1, 2, 3])

In [12]:
torch.manual_seed(87)#正常來說每次產生的值為0~1之隨機值 可用此方式固定
x = torch.rand(2, 3, 4)
x

tensor([[[0.0036, 0.8931, 0.4548, 0.9815],
         [0.5443, 0.1487, 0.0450, 0.5285],
         [0.6307, 0.6676, 0.3723, 0.8175]],

        [[0.1480, 0.5822, 0.1032, 0.3165],
         [0.9750, 0.1861, 0.9619, 0.9053],
         [0.7163, 0.3249, 0.4789, 0.0177]]])

In [16]:
x = torch.zeros(3, 4)
x

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [15]:
y = torch.ones(3 ,4)
y

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [17]:
x = torch.arange(0, 11, 2)
x

tensor([ 0,  2,  4,  6,  8, 10])

In [20]:
x = torch.tensor([0.1, 0.2, 0.3],
                 dtype=None,#資料型態 預設為自動感應
                 device=None,#運行的設備 預設為cpu
                 requires_grad=False)#是否追蹤梯度
x.dtype, x.device, x.requires_grad

(torch.float32, device(type='cpu'), False)

In [23]:
#取值和數值改變
x = torch.tensor([[0.1, 0.2, 0.3],
                 [0.4, 0.5, 0.6]])
x[0][0]

tensor([[1.1000, 1.2000, 1.3000],
        [1.4000, 1.5000, 1.6000]])

In [24]:
x = torch.tensor([[0.1, 0.2, 0.3],
                 [0.4, 0.5, 0.6]])
x+1

tensor([[1.1000, 1.2000, 1.3000],
        [1.4000, 1.5000, 1.6000]])

In [25]:
#矩陣相乘
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])

y = torch.tensor([[1, 2, 3],
                  [4, 5, 6]])

torch.matmul(x, y)

tensor([[ 9, 12, 15],
        [19, 26, 33],
        [29, 40, 51]])

In [26]:
#轉置
x = torch.tensor([[1, 2],
                  [3, 4],
                  [5, 6]])

x.T

tensor([[1, 3, 5],
        [2, 4, 6]])

In [28]:
x = torch.arange(0, 10)
x.reshape(2, 5)#注意改變的值要和原本一樣

tensor([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]])

In [29]:
#矩陣轉張量
import numpy as np

array = np.array([1, 2, 3])
tensor = torch.from_numpy(array)
array, tensor

(array([1, 2, 3]), tensor([1, 2, 3], dtype=torch.int32))

In [30]:
#張量轉矩陣
tensor = torch.tensor([1, 2, 3])
array = tensor.numpy()
tensor, array

(tensor([1, 2, 3]), array([1, 2, 3], dtype=int64))